config/routes.rb
Rails.application.routes.draw do
  resources :products
  root to: 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :walmart_id, :name, :price, presence: true
  has_many :reviews, dependent: :destroy

  def self.currency
    '$' # hardcoded for now, though possibly can be retreived via Walmart API
  end
end

app/models/review.rb
class Review < ApplicationRecord
  validates :title, :body, :product_id, presence: true

  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ApplicationHelper

  def index
    @products = Product.all
  end

  def new
  end

  def create
    unless valid_url?(product_params[:product_url])
      redirect_to(new_product_path, alert: 'invalid walmart url') && return
    end

    @product = Walmart::WalmartProductCreateService.new(product_params[:product_url], product_params[:review_black_list]).create_or_update_product

    unless @product
      redirect_to(new_product_path, alert: 'product import failed, correct url and try again') && return
    end

    redirect_to product_path(@product)
  end

  def show
    @product = Product.includes(:reviews).find(product_params[:id])
  end

  private
  def product_params
    params.permit(:id, :product_url, :review_black_list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'uri'

  def price(cents)
    return '' unless cents.is_a?(Integer) || (cents > 0)
    "#{Product.currency}#{cents/100}"
  end

  def valid_url?(uri)
    uri = URI.parse(uri)
  rescue URI::InvalidURIError
    false
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Walmartfetcher</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <p id="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.haml
%h1 Walmart fetcher

= link_to 'import product', new_product_path

- @products.each do |product|
  %h3= link_to product.name, product_path(product)
  %h4
    price:
    = price(product.price)

app/views/products/new.html.haml
= link_to 'Products list', products_path
%h1 Import product from Walmart

= form_tag('/products') do
  .fields
    = text_field_tag 'product_url', nil, placeholder: 'Walmart product url', class: 'input-large'
    %br
    do not import reviews with words:
    %br
    = text_field_tag 'review_black_list', nil, placeholder: 'words separated by commas', class: 'input-large'
  = submit_tag 'Import'

app/views/products/show.html.haml
= link_to 'Products list', products_path
%h1= @product.name
price: 
= price(@product.price)

%h2 product reviews

- @product.reviews.each do | review|
  %div
    %h4=review.title
    submission time:
    = review.submission_time
    %br
    reviewer:
    = review.reviewer
    %br
    overall rating:
    = review.overall_rating
    %br
    = review.body
  %hr